/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ball.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { useSphere } from "@react-three/cannon";

export function Ball(props) {
  const { nodes, materials } = useGLTF('/models/ball.glb')
  const args = [.22]

  const [ref] = useSphere(
    () => ({
      args,
      mass: 20,
      position: props.position
    }),
    useRef(null),
  )
  return <>

    <mesh castShadow receiveShadow>
    <sphereGeometry args={args} />
    <meshStandardMaterial transparent={true} opacity={0.25} />
  </mesh>

    <group ref={ref} {...props} dispose={null}>
      <group scale={.2}>
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  </>
}

useGLTF.preload('/models/ball.glb')
