/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cat_headup-final.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CatUp(props) {
  const { nodes, materials } = useGLTF('/models/catUp.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.peau} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['rose peau']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.yeux} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['peau blanche']} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials.Material} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/models/catUp.glb')
