/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cheese_export.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cheese(props) {
  const { nodes, materials } = useGLTF('/models/cheese.glb')
  return (
    <group {...props} scale={0.15} dispose={null}>
      <mesh geometry={nodes.cheese.geometry} material={materials.Material} position={[0, 1, 0]} />
    </group>
  )
}

useGLTF.preload('/models/cheese.glb')
