/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 portal_export.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Portal(props) {
  const { nodes, materials } = useGLTF('/models/portal.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.5} position={[-0.5, 0, -0.3]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['portal.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/portal.glb')
