/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rake_export.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { ColliderBox } from './ColliderBox'

export function Rake(props) {
  const { nodes, materials } = useGLTF('/models/rake.glb')
  return <>
    {<><ColliderBox position={props.position} scale={[1.7, .5, 0.07]} dpos={[.88,0,0]} />
      <ColliderBox position={props.position} scale={[.05, .8, 1]} dpos={[0,0,0]} /></>}

    <mesh {...props}>
      <group scale={.1} dispose={null}>
        <group position={[0.36, 0.36, 0]} scale={0.29}>
          <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.rake_head.geometry} material={materials['Material.001']} position={[0.7, 0.32, 0]} scale={0.85} />
      </group>
    </mesh>    
  </>
}

useGLTF.preload('models/rake.glb')
