/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 stick_short_export.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { ColliderBox } from './ColliderBox'

export function StickShort(props) {
  const { nodes, materials } = useGLTF('/models/stickShort.glb')
  return <>
   {<ColliderBox position={props.position} scale={[1.1, 0.9, 0.22]} dpos={[0.8,0,.05]} />}
   <mesh {...props}>
    <group scale={.08} dispose={null}>
      <mesh geometry={nodes.stick_short.geometry} material={materials.wood} position={[0, 1, 0]} />
    </group>
   </mesh>
   </>
}

useGLTF.preload('models/stickShort.glb')
