/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree5.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree5(props) {
  const { nodes, materials } = useGLTF('/models/tree5.glb')
  return (
    <group {...props} dispose={null} scale={0.07}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.008']} position={[0.48, 12.89, -0.11]} scale={1.8} />
    </group>
  )
}

useGLTF.preload('/models/tree5.glb')
