/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree1.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree1(props) {
  const { nodes, materials } = useGLTF('/models/tree1.glb')
  return (
    <group {...props} dispose={null} scale={0.15}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.002']} position={[0.14, 5.93, -1.75]} scale={0.94} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.003']} position={[-1.26, 6.18, -2]} rotation={[0.64, -1.18, 0.18]} scale={0.89} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.001']} position={[-0.86, 6.8, -0.33]} scale={1.23} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.006']} position={[-3.21, 7.51, 3.18]} rotation={[0.07, 0.92, 0.59]} scale={1.51} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.004']} position={[-1.1, 6.63, 3.22]} rotation={[0.21, 0.36, -0.12]} scale={1.01} />
      <mesh geometry={nodes.Icosphere005.geometry} material={materials['Material.005']} position={[-2.7, 6.63, 0.53]} rotation={[1.08, 1.17, -1.21]} scale={1.25} />
    </group>
  )
}

useGLTF.preload('/models/tree1.glb')
