/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree2(props) {
  const { nodes, materials } = useGLTF('/models/tree2.glb')
  return (
    <group {...props} dispose={null} scale={0.15}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.014']} position={[-0.19, 5.41, 4.06]} rotation={[-0.07, -0.33, -0.57]} scale={2.9} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.013']} position={[-2.79, 5.61, 2.72]} rotation={[1.05, -0.28, 0.11]} scale={4.23} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.012']} position={[-4.67, 5.39, -0.48]} rotation={[0.82, -0.01, 0.75]} scale={3.28} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.011']} position={[-3.41, 5.64, -2.2]} rotation={[1.06, -0.71, 0.64]} scale={2.03} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.010']} position={[-1.62, 6.4, -1.58]} rotation={[0.35, 0.43, -0.87]} scale={3.52} />
      <mesh geometry={nodes.Icosphere005.geometry} material={materials['Material.009']} position={[0.63, 6.67, -0.96]} rotation={[-0.06, -0.7, 0.42]} scale={2.92} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.008']} position={[2.33, 6.02, 1.82]} rotation={[0.65, -0.76, 0.94]} scale={4.44} />
    </group>
  )
}

useGLTF.preload('/models/tree2.glb')
