/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree3(props) {
  const { nodes, materials } = useGLTF('/models/tree3.glb')
  return (
    <group {...props} dispose={null} scale={0.12}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.008']} position={[-1.2, 8.54, 0.4]} scale={1.54} />
    </group>
  )
}

useGLTF.preload('/models/tree3.glb')
