/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree6.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree6(props) {
  const { nodes, materials } = useGLTF('/models/tree6.glb')
  return (
    <group {...props} dispose={null} scale={0.07}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.008']} position={[0.59, 12.73, 0.25]} rotation={[-0.33, -0.21, -0.77]} scale={1.88} />
    </group>
  )
}

useGLTF.preload('/models/tree6.glb')
