/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree4.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree4(props) {
  const { nodes, materials } = useGLTF('/models/tree4.glb')
  return (
    <group {...props} dispose={null} scale={0.12}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.008']} position={[0.16, 6.61, -0.21]} scale={1.18} />
    </group>
  )
}

useGLTF.preload('/models/tree4.glb')
